apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html
data:
  index.html: |
    <html>
      <head><title>Hello</title></head>
      <body>
        <h1>Hello World from Helm + NGINX 🚀</h1>
      </body>
    </html>
